syntax = "proto3";

package gfs;

service MasterService {

  rpc GetPrimary(Empty)
      returns (PrimaryResponse);

  rpc Heartbeat(ServerInfo)
      returns (HeartbeatAck);

  rpc GetStatus(Empty)
      returns (StatusResponse);

  rpc RegisterNode(NodeInfo)
      returns (RegisterResponse);

  rpc GetNodes(Empty)
      returns (NodeList);
  rpc MasterHeartbeat(Empty)
      returns (HeartbeatAck);

}

service ChunkService {

  rpc WriteChunk(WriteRequest)
      returns (WriteResponse);

  rpc ReadChunk(ReadRequest)
      returns (ReadResponse);

  rpc ReplicateChunk(WriteRequest)
      returns (WriteResponse);
  rpc SyncChunk(ReadRequest)
      returns (ReadResponse);
  rpc ListChunks(Empty)
      returns (ChunkList);
}

message Empty {}

message PrimaryResponse {
  string primary_id = 1;
  string primary_address = 2;
}

message ServerInfo {
  string server_id = 1;
}

message HeartbeatAck {
  string status = 1;
}

message WriteRequest {
  string chunk_id = 1;
  string data = 2;
}

message WriteResponse {
  string status = 1;
}

message ReadRequest {
  string chunk_id = 1;
}

message ReadResponse {
  string data = 1;
}

message NodeInfo {
  string node_id = 1;
  string address = 2;
}

message RegisterResponse {
  string status = 1;
}

message ChunkList {

  repeated string chunks = 1;
}

message StatusResponse {

  string primary = 1;

  string server1 = 2;

  string server2 = 3;

  string server3 = 4;

  int32 lease_remaining = 5;
}

message NodeEntry {

 string node_id = 1;

 string address = 2;
}

message NodeList {

 repeated NodeEntry nodes = 1;
}