# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared import gfs_pb2 as gfs__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gfs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MasterServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPrimary = channel.unary_unary(
                '/gfs.MasterService/GetPrimary',
                request_serializer=gfs__pb2.Empty.SerializeToString,
                response_deserializer=gfs__pb2.PrimaryResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/gfs.MasterService/Heartbeat',
                request_serializer=gfs__pb2.ServerInfo.SerializeToString,
                response_deserializer=gfs__pb2.HeartbeatAck.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/gfs.MasterService/GetStatus',
                request_serializer=gfs__pb2.Empty.SerializeToString,
                response_deserializer=gfs__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RegisterNode = channel.unary_unary(
                '/gfs.MasterService/RegisterNode',
                request_serializer=gfs__pb2.NodeInfo.SerializeToString,
                response_deserializer=gfs__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.GetNodes = channel.unary_unary(
                '/gfs.MasterService/GetNodes',
                request_serializer=gfs__pb2.Empty.SerializeToString,
                response_deserializer=gfs__pb2.NodeList.FromString,
                _registered_method=True)
        self.MasterHeartbeat = channel.unary_unary(
                '/gfs.MasterService/MasterHeartbeat',
                request_serializer=gfs__pb2.Empty.SerializeToString,
                response_deserializer=gfs__pb2.HeartbeatAck.FromString,
                _registered_method=True)


class MasterServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetPrimary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MasterHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPrimary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrimary,
                    request_deserializer=gfs__pb2.Empty.FromString,
                    response_serializer=gfs__pb2.PrimaryResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=gfs__pb2.ServerInfo.FromString,
                    response_serializer=gfs__pb2.HeartbeatAck.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=gfs__pb2.Empty.FromString,
                    response_serializer=gfs__pb2.StatusResponse.SerializeToString,
            ),
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=gfs__pb2.NodeInfo.FromString,
                    response_serializer=gfs__pb2.RegisterResponse.SerializeToString,
            ),
            'GetNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodes,
                    request_deserializer=gfs__pb2.Empty.FromString,
                    response_serializer=gfs__pb2.NodeList.SerializeToString,
            ),
            'MasterHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.MasterHeartbeat,
                    request_deserializer=gfs__pb2.Empty.FromString,
                    response_serializer=gfs__pb2.HeartbeatAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gfs.MasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gfs.MasterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MasterService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPrimary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.MasterService/GetPrimary',
            gfs__pb2.Empty.SerializeToString,
            gfs__pb2.PrimaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.MasterService/Heartbeat',
            gfs__pb2.ServerInfo.SerializeToString,
            gfs__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.MasterService/GetStatus',
            gfs__pb2.Empty.SerializeToString,
            gfs__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.MasterService/RegisterNode',
            gfs__pb2.NodeInfo.SerializeToString,
            gfs__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.MasterService/GetNodes',
            gfs__pb2.Empty.SerializeToString,
            gfs__pb2.NodeList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MasterHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.MasterService/MasterHeartbeat',
            gfs__pb2.Empty.SerializeToString,
            gfs__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChunkServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteChunk = channel.unary_unary(
                '/gfs.ChunkService/WriteChunk',
                request_serializer=gfs__pb2.WriteRequest.SerializeToString,
                response_deserializer=gfs__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.ReadChunk = channel.unary_unary(
                '/gfs.ChunkService/ReadChunk',
                request_serializer=gfs__pb2.ReadRequest.SerializeToString,
                response_deserializer=gfs__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.ReplicateChunk = channel.unary_unary(
                '/gfs.ChunkService/ReplicateChunk',
                request_serializer=gfs__pb2.WriteRequest.SerializeToString,
                response_deserializer=gfs__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.SyncChunk = channel.unary_unary(
                '/gfs.ChunkService/SyncChunk',
                request_serializer=gfs__pb2.ReadRequest.SerializeToString,
                response_deserializer=gfs__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.ListChunks = channel.unary_unary(
                '/gfs.ChunkService/ListChunks',
                request_serializer=gfs__pb2.Empty.SerializeToString,
                response_deserializer=gfs__pb2.ChunkList.FromString,
                _registered_method=True)


class ChunkServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def WriteChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChunkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteChunk,
                    request_deserializer=gfs__pb2.WriteRequest.FromString,
                    response_serializer=gfs__pb2.WriteResponse.SerializeToString,
            ),
            'ReadChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadChunk,
                    request_deserializer=gfs__pb2.ReadRequest.FromString,
                    response_serializer=gfs__pb2.ReadResponse.SerializeToString,
            ),
            'ReplicateChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateChunk,
                    request_deserializer=gfs__pb2.WriteRequest.FromString,
                    response_serializer=gfs__pb2.WriteResponse.SerializeToString,
            ),
            'SyncChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncChunk,
                    request_deserializer=gfs__pb2.ReadRequest.FromString,
                    response_serializer=gfs__pb2.ReadResponse.SerializeToString,
            ),
            'ListChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChunks,
                    request_deserializer=gfs__pb2.Empty.FromString,
                    response_serializer=gfs__pb2.ChunkList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gfs.ChunkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gfs.ChunkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChunkService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.ChunkService/WriteChunk',
            gfs__pb2.WriteRequest.SerializeToString,
            gfs__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.ChunkService/ReadChunk',
            gfs__pb2.ReadRequest.SerializeToString,
            gfs__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.ChunkService/ReplicateChunk',
            gfs__pb2.WriteRequest.SerializeToString,
            gfs__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.ChunkService/SyncChunk',
            gfs__pb2.ReadRequest.SerializeToString,
            gfs__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.ChunkService/ListChunks',
            gfs__pb2.Empty.SerializeToString,
            gfs__pb2.ChunkList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
